apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-apic
spec:
  encryptedData:
    .dockerconfigjson: AgCa785Rrtid/6v6bbZsFXAyAaBqW0HxZZoYxyISFc8Eej1XELnIf9p20DcaVv2y2CaB1YqoHXWNHOPonydXS846G83eIBHa9Z6VIEHYQy7qAAYXcTE7oMwMg9WDyBALqse3g87BhiAAUlMBhO1Zt4j2JWgc4rzJzQvAJf81L6f7l6HIrSRI3NzzvbBNFJpyLtneJEsxdrF6zWIkQZYb4W78g2WlaCxa26G8T0rxZrS5G5Bs/uSml99djFzPW4uYXULOPNB807K/JYd/CU+egLrUFBx1k2fx6xktMp/Yxk3/9HHE4yCNpAw+fCPbhT9IRR7K8lVEqktk5YoTrkzIVk/T/apXRbJbkaWFUD9rwyizp8tBM9qKHSZGidFly+BczcKwJjjNOv1qN8OSy9prZ5QW2c6O/y7Ursdqgnzt4O3KZXZZ12yuAGUqXg1QVtpAf93m4yMIqktWipNu84/VseUGERku4ynd250RrsT19qytEw+MiLNl7wEp1dIseUEGcYxk4aFXmn+8QV50vN4OqXPVqClhpFZeUcSBTqGxZPDAfyKfT7QhIT4cMTMk+xBTbzXowpRFZhn/xK/iZp4kFhQQdGNzQ9n4e22D6vCxOOUaN2xrH0TrisJ6oa7w9k4TE8Z9ACNszbmvaUY/EGyb08NEFcKaF1VqqFhrFvih73nySdwiaCB3MGWUal/FI8Zyz8t3q0x4Yi7K6CCvniD5qwbJHjoTBePuPOzcpljy5Tbi1QAh1IgA57xX1/O/hKIBJRL9YlVCyX6AYjFnuP7lWT16smI9jevvKb2b1vtRHFTKvWIS29R9cdftyjbOBPpQdS9fsbxgLD6Whr8rj0KhrQUZd8/E2DcHN7BFYMWxfCCk7igZViKbYtRoPfdqxi0Pl90OJ1SHOZvj2hi/TWJ+SYIoRGSQ1elmabKs249/oxNkNyX1RIxTBlu1Be4ZYBIqsdW0DboHPZQTP3OlIQzaA6zJ+cUgTiv6pXzBKS0rno8eeod4bjEy1hsMlzud5LZACLB2wNj89HXX7XbpOShCi+3hZKHIvR47fmdG48T4UnVlYYo4SUGVCDUCbolE1TbOIwFtjmxfwqF8QdrXYFNR9Sd1HpvDN7PRQu+Ri4uFwYH34adYCOUNNz14F5BKPVJW38vD1MgqJcYJ4fqhvSJ3KU06cBIc6FtsSzauycSBp/6SXd3CWqJVF9H7d9WJQT7h9dN8zUVzU5OdJ0k0FkdoVOwJIdatTgQbLZcrCdp2ox53HLNB/par6Ao8MAgVfw7uIBPm6AHpPU0xrVL4aLLoW3+W+8b2dkIA1n74f/kCmDY4/FCVdyiiYBlSzhZu2v/gxpIg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-apic
    type: kubernetes.io/dockerconfigjson

